language: objective-c

osx_image: xcode9
script:
- xcodebuild -project TicTacToe/TicTacToe.xcodeproj -scheme TicTacToe build CODE_SIGNING_REQUIRED=NO  ONLY_ACTIVE_ARCH=NO  RUN_CLANG_STATIC_ANALYZER=YES GCC_TREAT_WARNINGS_AS_ERRORS=YES

notifications:
  slack: 'samedialabs:$SLACK_SAMEDIALABS_TRAVIS_CI'

