language: objective-c

osx_image: xcode10

script:
- xcodebuild -workspace TicTacToe.xcworkspace -scheme TicTacToe -destination 'platform=iOS Simulator,name=iPhone 8' clean build CODE_SIGNING_REQUIRED=NO  ONLY_ACTIVE_ARCH=NO  RUN_CLANG_STATIC_ANALYZER=YES

notifications:
    slack: samedialabs:4HGYk0UNrHO3pRwlyMjsFdkX


