language: objective-c

osx_image: xcode9
script:
- xcodebuild -workspace TicTacToe.xcworkspace -scheme TicTacToe -destination 'platform=iOS Simulator,id=ABBD7191-486B-462F-80B4-AE08C5820DA1' CODE_SIGNING_REQUIRED=NO  ONLY_ACTIVE_ARCH=NO  RUN_CLANG_STATIC_ANALYZER=YES GCC_TREAT_WARNINGS_AS_ERRORS=YES

notifications:
  slack: 'samedialabs:$SLACK_SAMEDIALABS_TRAVIS_CI'

